version: "3"

services:
  backend:
    build:
      context: ./backend
    # image: soe153/projectmanagement-backend:latest
    environment:
      APP_ENV: local

    # depends_on:
    #   - mysql
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./backend:/app
      - /app/vendor

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sithu
      MYSQL_DATABASE: university_magazine
      MYSQL_USER: sithu
      MYSQL_PASSWORD: sithu
    ports:
      - "0.0.0.0:3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: sithu # Update this to match your MySQL user
      PMA_PASSWORD: sithu # Update this to match your MySQL password
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
    command: ["apache2-foreground"]
